### ISSUE TITLE
Scrollbar handle disappears in pdf viewer when using dark mode

### ISSUE THREAD

**Issue by DavidPgl** [Sansui233/logseq-bonofix-theme#14]
It is still there and usable.

Dark Mode with no scrollbar handle:
![image](https://user-images.githubusercontent.com/35039404/168828116-7da7f1fb-b01b-4493-a8f6-76167500e27e.png)

Light Mode with scrollbar handle:
![image](https://user-images.githubusercontent.com/35039404/168827745-113edc2d-5f83-48fa-a1bb-0f966b180429.png)

When using the logseq color as the background for the pdf, the handle is visible:
![image](https://user-images.githubusercontent.com/35039404/168828612-39b7c7c0-bc7d-4eda-ad53-64ad3de0057e.png)

With white and beige as the background color the handle is not visible.

(Great theme btw, love the contrast when quoting and using tags 🙏)

**Comment by Sansui233** [comment]
Thanks a lot. Now the thumb color works for both white and black background in dark mode.
