### ISSUE TITLE
暗黑模式下高亮文字颜色错误

### ISSUE THREAD

**Issue by mendax1234** [Sansui233/logseq-bonofix-theme#15]
暗黑模式下高亮文字的颜色显示不出来，效果如下图所示
![image](https://user-images.githubusercontent.com/62934294/169694715-fedd99fd-d3f8-41f3-b18a-1a707d16b071.png)
其中“高温”一字本来是红色高亮
![image](https://user-images.githubusercontent.com/62934294/169694732-c209d3aa-67dc-4332-b19a-91d4caad9087.png)
在浅色模式下则正常
希望能尽快解决！

**Comment by Sansui233** [comment]
请注明你所使用 logseq 版本、平台，以及该语句的 markdown 语法。因为这个主题中的高亮文字是带边距的黄色背景，非红色文字，而你的截图中light mode 下文字为红色，dark mode 的背景也没有边距，我无法复现此问题。

<img width="743" alt="image" src="https://user-images.githubusercontent.com/27474981/169695568-66e8548b-60a9-4f37-88c3-6120752bdf99.png">
<img width="747" alt="image" src="https://user-images.githubusercontent.com/27474981/169695579-82e2c9a3-1a94-4921-a1c7-64bc227c4d85.png">

其中 dark mode 下背景色黄较浅，是因为此主题 dark mode 设定的使用场景为夜晚周围无光源，而非白天适用的黑色模式。在黑暗环境中人眼对于色彩的对比度会更加敏感，因此减弱了明度与饱和度的对比，以减少夜晚观看屏幕对人眼的刺激。

如果有自定义需求可以参考 #13 所说方式进行自定义。

**Comment by mendax1234** [comment]
课我在白天模式下是没有黄色边框的啊

**Comment by Sansui233** [comment]
> 课我在白天模式下是没有黄色边框的啊

对，所以请注明你所使用 logseq 版本、操作系统、bonofix 版本，否则我无法复现。如果你会调试也可以打开元素检查器看看，把 css 属性截个图。

**Comment by mendax1234** [comment]
logseq 0.6.9，windows10 pro，bonofix 3.6.6

**Comment by mendax1234** [comment]
希望能尽快修复，谢谢！

**Comment by Sansui233** [comment]
已用和你相同的环境 测试，确认主题没有问题。问题应该出在有其他地方的样式造成了干扰。

你可以按以下步骤检查：

1. 重启 logseq app，样式错误是否仍然出现（如果你在之前频繁切换过别的主题，样式可能会被影响）
2. 切换为默认主题，light mode 下是否仍然文字为红色
3. 你仓库中的 custom.css 文件内容是否清空？如果自定义过，样式会被影响。

<img width="218" alt="屏幕截图 2022-05-22 215802" src="https://user-images.githubusercontent.com/27474981/169698872-b86b209c-5e51-4d20-a6ef-e674a7573074.png">
<img width="232" alt="屏幕截图 2022-05-22 215848" src="https://user-images.githubusercontent.com/27474981/169698874-defa6baa-b555-4e15-a922-0471a3372bbb.png">

**Comment by mendax1234** [comment]
可是我原来light模式下是红色字体，暗黑模式下就不是红色字体了，我不是黄色高亮

**Comment by Sansui233** [comment]
> 可是我原来light模式下是红色字体，暗黑模式下就不是红色字体了，我不是黄色高亮

 1. 能否告知我以上三个检查每一步的结果？
 2. 以及你说的“原来”是指默认主题吗？如果是，那这个问题请在确认完上述第三步检查后，咨询 Logseq 官方。因为官方默认样式也不是红色文字。

**Comment by mendax1234** [comment]
>重启 logseq app，样式错误是否仍然出现（如果你在之前频繁切换过别的主题，样式可能会被影响）
是的
>切换为默认主题，light mode 下是否仍然文字为红色
是的，文字是红色
>你仓库中的 custom.css 文件内容是否清空？如果自定义过，样式会被影响。
我从来没有修改过custom.css
>以及你说的“原来”是指默认主题吗？如果是，那这个问题请在确认完上述第三步检查后，咨询 Logseq 官方。因为官方默认样式也不是红色文字。
我说的“原来”指的是bonofix主题，我没用官方的高亮，我用的是一个插件，叫‘Text Wrapper’。但是我换了其他的主题，用的还是这个插件，就没有任何问题。所以这是主题的问题，而不是官方的问题，希望得到解决！谢谢

**Comment by Sansui233** [comment]
@mendax1234 感谢提供信息，明白了，这是方主题与 Text wrapper 的样式冲突问题。由于 Text Wrapper 的样式没有适配 dark mode，导致它的高亮样式覆盖能力不足。

个人认为最好的解决方式是由 Text wrapper 插件增强其样式覆盖能力以解决与主题间的冲突，而非每个主题对插件进行适配。除了 Bonofix 主题，修改了夜间高亮颜色的 logseq-dev-theme 在使用 Text wrapper 高亮背景的情况下文字也不可读。尽管主题可以在当前适配该插件，但后续也无法跟踪插件的样式更新。

此问题我将在 Text Wrapper 提出相应 issue，无法解决时再考虑将主题适配插件。

**Comment by mendax1234** [comment]
好的，多谢！

**Comment by Sansui233** [comment]
@mendax1234 Text Wrapper 已更新

**Comment by mendax1234** [comment]
好快，感谢！
