### ISSUE TITLE
日记前面的台历图标时间不对

### ISSUE THREAD

**Issue by mendax1234** [Sansui233/logseq-bonofix-theme#17]
![image](https://user-images.githubusercontent.com/62934294/169780087-75c59f78-e3a7-4740-8add-fc165f8a4a40.png)
希望能早日解决！谢谢

**Comment by Sansui233** [comment]
这个其实是使用的系统的日历 emoji 装饰， 改不了，除非换掉的 emoji 的字体。主题文件本身不包含任何需要动态生成的装饰。

相关 issue #3

**Comment by mendax1234** [comment]
好吧，那就先将就着用了

**Comment by mendax1234** [comment]
所以说目前无法实现，我觉得可以作为可增加的功能之一，这样整体的效果会挺不错的

**Comment by Sansui233** [comment]
@mendax1234 嗯，虽然我也想改这个，但这样就不是单纯主题能实现的了，得用插件。

**Comment by mendax1234** [comment]
>@Sansui233 请问能否提示一下在日期前加日历emoji的代码在哪里，谢谢
@Sansui233 能否提示一下日历相关代码在哪里，谢谢！

**Comment by mendax1234** [comment]
@Sansui233 请问你是如何在logseq上发布一个主题的

**Comment by Sansui233** [comment]
@mendax1234 邮件联系

**Comment by mendax1234** [comment]
@Sansui233 已发送邮件，请查收
