### ISSUE TITLE
zotero链接颜色不对

### ISSUE THREAD

**Issue by mendax1234** [Sansui233/logseq-bonofix-theme#18]
使用zotero打开pdf的时候，link的颜色一直都是红色，询问了相关人员，说是主题的问题，能帮忙看一下吗？谢谢
![image](https://user-images.githubusercontent.com/62934294/169803889-4444cbbb-1249-48e4-8df3-90ae1e61f317.png)
logseq版本：0.6.9，操作系统：Windows10 Pro

能否将链接的颜色改为蓝色？如下图，这样看起来可能会比较舒服
![image](https://user-images.githubusercontent.com/62934294/169804454-923c6663-5a14-4028-a639-a95ccb9c27de.png)

**Comment by Sansui233** [comment]
这个主题是红蓝双色配色， external link 一直都是红色， Logseq 内部 link 是蓝色。我感觉你的需求其实用自带的主题会更加适合，不喜欢的部分按自己的想法改改就可以了。

**Comment by Sansui233** [comment]
鉴于非颜色不对，暂时关闭此 issue

**Comment by mendax1234** [comment]
好吧
