### ISSUE TITLE
autocomplete popover menu selected item doesn't show

### ISSUE THREAD

**Issue by dwradcliffe** [Sansui233/logseq-bonofix-theme#19]
Something must have changed in a recent logseq release. Now when an autocomplete popover menu shows, and I try to use the arrows to select an item the selected item doesn't show any different than the unselected items.

I'm using theme v3.7.3 and Logseq 0.7.4.

To replicate, type `[[` to init the page autocomplete, then press the down arrow on your keyboard.

<img width="326" alt="image" src="https://user-images.githubusercontent.com/118850/173660855-1a778a8a-6cc7-488b-8995-f1be8451a1c7.png">

**Comment by Sansui233** [comment]
Thanks, fixed in v3.7.4
