### ISSUE TITLE
CSS to manipulate colouring of drop down

### ISSUE THREAD

**Issue by nickriches** [Sansui233/logseq-bonofix-theme#21]
Great theme which I use in dark mode. It's virtually perfect, except for one thing. When the drop down is generated, e.g. using forward-slash (see image below), it's very difficult to see which words are highlighted. Is there a DOM for this so I can tweak the CSS? (NB I have tried using developer mode, but I am not an expert at this). Thanks.

<img width="541" alt="dropdown" src="https://user-images.githubusercontent.com/7710405/192155773-b8daeaa0-3d76-49d0-a3c0-db45223d3063.png">

**Comment by Sansui233** [comment]
```css
.dark-theme .menu-link.chosen {}
```
Thanks for feedback, I'll take that into account.

**Comment by nickriches** [comment]
Excellent! Thank you.

**Comment by nickriches** [comment]
I tweaked the colour of the dropdown (see below). Colour is #5e7272. For me the colour works much better, though that's no guarantee that others will prefer it.

![image](https://user-images.githubusercontent.com/7710405/193224957-b64dd479-5038-4103-8144-b215994746ad.png)
