### ISSUE TITLE
Bonofix使用透明度颜色用于混合 导致Awesome UI的属性icon出现重叠与边框的Bug

### ISSUE THREAD

**Issue by Gitbreast** [Sansui233/logseq-bonofix-theme#25]
现象：使用Awesome UI时，Bonofix的属性icon出现重叠与多余方框。
> Default theme:
> <img width="572" alt="image" src="https://user-images.githubusercontent.com/96460796/218246263-0d9004f9-adf6-4d89-98b0-a701a7e24e6e.png">
> Bonofix theme:
> <img width="564" alt="image" src="https://user-images.githubusercontent.com/96460796/218246592-b27cee04-48e7-4e1d-abd7-70262cd76702.png">

Awesome UI作者表示是Bonofix所用的颜色使用了透明度导致：
> in the case of "Bonofix" - bg color is using transparency:
> 
> ![image](https://user-images.githubusercontent.com/137919/218249707-3f00a20c-ccb4-46d9-9887-4e0dc0f3ff70.png)
> 
> contact author to somehow solve it - https://github.com/Sansui233/logseq-bonofix-theme/issues

> Gitbreast: I see(a little bit), Bonofix uses a color with transparency to mix with default theme's color to get Bonofix's color, right? I'll issue it to Bonofix.

_Originally posted by @Gitbreast in https://github.com/yoyurec/logseq-awesome-ui/issues/45#issuecomment-1426708420_

Dev theme也有类似问题但原因不一样，好像是没用logseq的变量名而导致：https://github.com/pengx17/logseq-dev-theme/pull/87

是否直接使用混合后的非透明度颜色的值，这个Bug就会解决？

**Comment by Sansui233** [comment]
是的，但会导致另一个 Bug，右侧栏的 page-property 没有辨识度。

Default theme: 固定色
<img width="862" alt="Screen Shot 2023-02-14 at 17 07 36" src="https://user-images.githubusercontent.com/27474981/218692562-1a1039e1-9c35-4b68-a939-64a998702a4f.png">

Bonofix theme：透明色
<img width="833" alt="Screen Shot 2023-02-14 at 17 14 02" src="https://user-images.githubusercontent.com/27474981/218692595-21f87d64-43d2-4738-8a8a-2eefdbd17db5.png">

这是由于设计上背景的配色比较偏低对比度导致的。Dev theme 对比度较高，使用固定色的辨识度也还不错。

需要两者都没问题的话，目前暂定需要选四个色的方案（亮暗+黑白）。

急用的话，white-mode下可以使用一个算能看折中色。
```
.block-properties.page-properties {
  --ls-page-properties-background-color: #f0f0f0;
}
```
