### ISSUE TITLE
Top bar icons are not properly visible after updating

### ISSUE THREAD

**Issue by TalEdd** [Sansui233/logseq-bonofix-theme#36]
![image](https://github.com/Sansui233/logseq-bonofix-theme/assets/63492921/b4b0d0f4-f952-4db6-ab16-ae0ad35ae2ae)
Did I install it wrongly somehow? Am on the latest version.
![image](https://github.com/Sansui233/logseq-bonofix-theme/assets/63492921/9d57cfdf-59e5-4412-8826-5762847f882e)

**Comment by Sansui233** [comment]
fix in [8dbe984](https://github.com/Sansui233/logseq-bonofix-theme/commit/8dbe984cb53e9473e02e68ab749c026485a512f7)
