### ISSUE TITLE
Date Picker too wide after updating LogSeq to 0.10.7

### ISSUE THREAD

**Issue by colandre** [Sansui233/logseq-bonofix-theme#37]
I noticed that the date picker modal is too wide after updating to LogSeq version [0.10.7](https://github.com/logseq/logseq/releases/tag/0.10.7).
This prevents scrolling months and selecting dates correctly.

![image](https://github.com/Sansui233/logseq-bonofix-theme/assets/7578590/272592de-44f2-4e04-8407-763fa682bedc)

Disabling the BonoFix Theme, the date picker works correctly

![image](https://github.com/Sansui233/logseq-bonofix-theme/assets/7578590/c7f0c25b-bffd-4f1b-996c-786a478a67f9)

**Comment by justaprussian** [comment]
Confirmed, same here. See https://discuss.logseq.com/t/caused-by-bonofix-theme-schedule-suddenly-unusable/25571/2

**Comment by Sansui233** [comment]
Fixed in 06231da0d94fb6f8366eb4860554c1c6585cbd07
