### ISSUE TITLE
Selection color on research is barely visible

### ISSUE THREAD

**Issue by windboy91** [Sansui233/logseq-bonofix-theme#38]
The accent color of a selected element on the search or command palette is very hard to notice, especially on light mode.
![Enregistrement de l’écran 2024-04-04 à 16 08 55](https://github.com/Sansui233/logseq-bonofix-theme/assets/119671436/ef3dee90-a14d-49a5-80e6-a97164b582d5)

**Comment by Sansui233** [comment]
Which logseq version and theme version?
In Logseq v0.10.8 and Bonofix v3.10.3, it's shows as below:
![2024-04-04 222421](https://github.com/Sansui233/logseq-bonofix-theme/assets/27474981/749754e6-56f1-4f09-b102-1efebc87dd5f)

**Comment by windboy91** [comment]
Same version for both. Mine is not as contrasted

**Comment by Sansui233** [comment]
> Same version for both. Mine is not as contrasted
> I've identified an issue. The accent color in the design system doesn't perfectly match the default color. I'll address this in a future update.

**Comment by Sansui233** [comment]
It is currently fixed in the main branch but has not been released yet. More work is needed as Logseq is in the process of refactoring its design system. The old default color palette might be completely deprecated in the future.

**Comment by Sansui233** [comment]
Released in v3.10.4.

**Comment by windboy91** [comment]
Works perfectly now ! Thanks 😃
