### ISSUE TITLE
 The width of the scroll bar cannot be modified

### ISSUE THREAD

**Issue by operations4304** [Sansui233/logseq-bonofix-theme#39]
Hello, I really like this theme!

In the figure below, I have changed the width to 15px, but the scrollbar in Logseq has not widened.

![2024-07-02_194448](https://github.com/Sansui233/logseq-bonofix-theme/assets/155797197/21d41844-93ee-4853-8e1b-92474e476b70)

I don't know where the problem is, can you help me?

My Logseq version is 0.10.9 on the Windows platform.

**Comment by Sansui233** [comment]
New css variable: 
```css
:root {
  --ls-scrollbar-width: 15px;
}
```
You remind me that here are some incompabilities in recent versions, like the scrollbar  thumb doesn't display correctly.

**Comment by operations4304** [comment]
Useful, thank you very much!
