### ISSUE TITLE
pdf标注的时候不显示高亮颜色

### ISSUE THREAD

**Issue by YangWaldon** [Sansui233/logseq-bonofix-theme#4]
![image](https://user-images.githubusercontent.com/49675185/141218331-5ee8660c-d4da-48ff-bd35-46740bddfcbf.png)

**Comment by Sansui233** [comment]
我这边可以进行标注以及显示标注的颜色。这个主题没有对 PDF 标注进行改动。

可以考虑如下操作确定是哪里的问题：
- 换一个主题是否可以显示？如果可以显示，再换回来是否可以显示？
- 换一个 PDF 是否可以显示？

![image](https://user-images.githubusercontent.com/27474981/141278862-ead34ed4-3cfa-415b-99b1-1bd591abd3e3.png)

**Comment by MrVPlusOne** [comment]
我这边也遇到了一样的问题。关闭bonofix-theme后可以正常显示，打开theme后标注不可见。并且我发现这个问题只在切换成dark theme时出现，light theme则显示正常。是因为dark theme的css无意将某个颜色设置为了透明吗？

**Comment by Sansui233** [comment]
> 我这边也遇到了一样的问题。关闭bonofix-theme后可以正常显示，打开theme后标注不可见。并且我发现这个问题只在切换成dark theme时出现，light theme则显示正常。是因为dark theme的css无意将某个颜色设置为了透明吗？

我这边的 Desktop App 还是没法复现😅 dark theme 和 light theme 都挺正常的。看了一下 PDF 标注用的 CSS 选择器，是以`.hls-text-region-item[data-color=yellow]`，是我没有设置过的。没法复现我很难知道是什么问题。

如果可以麻烦提供一下能出现这个问题的最小 Graph（不含个人敏感数据）。

或者自己能调试也可以，用 ctrl + alt + i 打开元素检查器，在标注生效时，用这个工具查看高亮的 CSS 类，再切到 Dark Theme，看这个类是否消失，值是否被覆盖
![image](https://user-images.githubusercontent.com/27474981/143240272-c2a24627-8552-42d0-b35a-3ca1aedcd106.png)

正常情况：
![image](https://user-images.githubusercontent.com/27474981/143241967-64c774b9-2ff6-4afd-9030-7c2686d31904.png)

**Comment by MrVPlusOne** [comment]
我用元素检查器调试了一下，问题似乎是由于[这一段dark theme独有的css](https://github.com/Sansui233/logseq-bonofix-theme/blob/2dc572dc00bdaf4ed959071ccd9afc6c47f050e8/custom.css#L555-L557)导致的。如果我在custom.css里面override 
```css
.dark-theme ::selection {
  background: #2ea6de7d;
}
```
标注则能显示正常。

**Comment by Sansui233** [comment]
> 我用元素检查器调试了一下，问题似乎是由于[这一段dark theme独有的css](https://github.com/Sansui233/logseq-bonofix-theme/blob/2dc572dc00bdaf4ed959071ccd9afc6c47f050e8/custom.css#L555-L557)导致的。如果我在custom.css里面override
> 
> ```css
> .dark-theme ::selection {
>   background: #2ea6de7d;
> }
> ```
> 
> 标注则能显示正常。

啊，是指选择文字时的颜色被覆盖……明白了，感谢，

**Comment by Sansui233** [comment]
fixed in 9b1a9e7
