### ISSUE TITLE
Block refs of scheduled task show extra empty row in the end of refed block

### ISSUE THREAD

**Issue by xoyk** [Sansui233/logseq-bonofix-theme#5]
![Screenshot 2021-12-06 at 12 34 39](https://user-images.githubusercontent.com/1499826/144822390-6f6f9255-b04b-48be-a58c-b7ee54931897.png)
![Screenshot 2021-12-06 at 12 34 26](https://user-images.githubusercontent.com/1499826/144822404-b47a4a21-8a9c-4ecd-b63f-cb569c87a9ce.png)

Looks like the part with "schedule info" generates the empty line

**Comment by Sansui233** [comment]
Fixed in #2226fb5. The block property `<div>` wrapped in the inline block reference can break line before right padding. Now the horizontal padding space is removed.
