### ISSUE TITLE
Calculator results are not lined up with equation

### ISSUE THREAD

**Issue by dwradcliffe** [Sansui233/logseq-bonofix-theme#7]
The calculator results are higher than the equation lines.

Screenshot:
![image](https://user-images.githubusercontent.com/118850/148469430-72069528-9a80-4ae0-8a18-24d4958442da.png)

Running MacOS desktop app
Logseq version 0.5.8
Theme version 3.5.10

**Comment by Sansui233** [comment]
Thank you. Fixed in v3.5.11
