### ISSUE TITLE
演示截图中右侧边栏的 Favorite 和 tag 列表是如何实现的？

### ISSUE THREAD

**Issue by Explorare** [Sansui233/logseq-bonofix-theme#8]
我看截图中能够在右侧显示一个可编辑的 favorite 页面，这个页面是如何实现的？而且还能显示 tags 列表，这个列表是手动编辑的么？我试了这个 query 把 journals 的日期 tag 也给包括进来了，内容很乱。
```
Query example:  "All page tags"
#+BEGIN_QUERY
{:title "All page tags"
:query [:find ?tag-name
      :where
      [?tag :page/name ?tag-name]]
:view (fn [tags]
      [:div
       (for [tag (flatten tags)]
         [:a.tag.mr-1 {:href (str "/page/" tag)}
          (str "#" tag)])])}
#+END_QUERY
```
如果方便的话能否指点一下，谢谢。

**Comment by Sansui233** [comment]
是默认的 Content 页面。内容都是手动编辑的，算是自己的 Graph 里常用的导航。在之前的版本中是没有左侧栏的，当时用 Content
页自己做了导航。那个页面可以随意编写，不一定作为导航使用。

Explorare ***@***.***> 于2022年2月21日周一 22:32写道：
