### ISSUE TITLE
Visual gaps at different indent depths

### ISSUE THREAD

**Issue by owiecc** [Sansui233/logseq-bonofix-theme#9]
There are visual gaps that form when there is a big difference in adjacent list indent depths. I would suggest to remove the bottom-padding in the list so that all the text lines follow a grid spacing, as in [CSS line grid](https://www.w3.org/TR/css-line-grid-1/).

![Screenshot 2022-02-27 at 11 50 18](https://user-images.githubusercontent.com/6896639/155879916-41901dbe-593b-4d45-898d-f87a6167bf76.png)

**Comment by Sansui233** [comment]
Now removed in the latest version. It was designed on purpose but seems over-designed.

**Comment by Sansui233** [comment]
After reading  notes for a long time, I find no visual section division makes it hard to read long articles, like a show without intermission. I'm going to adjust gap in the next version. The spacing will be remained but less obvious compared to the previous version.

E.g. 1
<img width="827" alt="Screen Shot 2022-03-08 at 16 25 24" src="https://user-images.githubusercontent.com/27474981/157196941-e0331143-c103-4fca-8a72-ef664e42c1d7.png">

E.g. 2
<img width="780" alt="Screen Shot 2022-03-08 at 16 26 06" src="https://user-images.githubusercontent.com/27474981/157196940-10d1946f-6ffe-445a-8f70-5e8e92d53404.png">

If you don't want it, consider adding these code to your custom.css.

```css
div[haschild="true"] > div.flex-row {
  margin-bottom: unset;
}
.block-children {
  margin-bottom: unset;
}
```
